# Generated by Django 4.2.13 on 2024-05-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='chat_type',
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('si', 'Single'), ('gr', 'Group')], max_length=2, null=True),
        ),
    ]
