# Generated by Django 4.2.13 on 2024-05-22 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_conversation_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'conversation')},
        ),
    ]
