# Generated by Django 4.2.13 on 2024-05-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_last_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
